sudo: true
dist: xenial
cache:
  timeout: 1024
  directories:
    - $HOME/.cargo

env:
  global:
    - RUST_BACKTRACE=full

matrix:
  include:
    - name: Rust
      language: rust
      rust: '1.33.0'
      install:
        - cargo fmt --version || rustup component add rustfmt-preview
        - cargo clippy --version || rustup component add clippy-preview
      script:
        - make ci-rust
    # - name: Rust (Big-endian)
    #   language: rust
    #   services: docker
    #   rust: '1.33.0'
    #   install:
    #     - cargo fmt --version || rustup component add rustfmt-preview
    #     - cargo clippy --version || rustup component add clippy-preview
    #     - rustup target add mips64-unknown-linux-gnuabi64
    #     - cross --version || cargo install cross --force
    #   script:
    #     - cross test --verbose
    - name: Python
      language: python
      python: '3.7'
      install:
        - export PIPENV_VERBOSITY=-1
        - pip install pipenv
        - pipenv install --dev
      script:
        - pipenv run python --version
        - make ci-python
    - name: Python (2.7)
      language: python
      python: '2.7'
      install:
        - export PIPENV_VERBOSITY=-1
        - pip install pipenv
        - pipenv install --dev
      script:
        - pipenv run python --version
        - make ci-python

before_cache:
- rm -rf $HOME/.cargo/registry
